### ISSUE TITLE
building llvm fails on intel mac

### ISSUE THREAD

**Issue by michaelknoch** [vgorloff/swift-everywhere-toolchain#111]
I followed the readme and tried to execute `node main.js bootstrap`, but the build fails early with the following error. @vgorloff any ideas how I can workaround that?

macos 11.3 with intel arch
node 12
xcode 12.5
cmake 3.19.4
ninja 1.10.2
ndk 21.3.6528147 properly linked to /usr/local/ndk

> -- clang project is enabled
-- clang-tools-extra project is disabled
-- compiler-rt project is disabled
-- debuginfo-tests project is disabled
-- libc project is disabled
-- libclc project is disabled
-- libcxx project is disabled
-- libcxxabi project is disabled
-- libunwind project is disabled
-- lld project is disabled
-- lldb project is disabled
-- llgo project is disabled
-- mlir project is disabled
-- openmp project is disabled
-- parallel-libs project is disabled
-- polly project is disabled
-- pstl project is disabled
-- Could NOT find Z3: Found unsuitable version "0.0.0", but required is at least "4.7.1" (found Z3_LIBRARIES-NOTFOUND)
-- Found libtool - /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
CMake Error at cmake/modules/CheckAtomic.cmake:53 (message):
  Host compiler appears to require libatomic, but cannot find it.
Call Stack (most recent call first):
  cmake/config-ix.cmake:334 (include)
  CMakeLists.txt:629 (include)

I guess thats the error:
```
CMake Error at cmake/modules/CheckAtomic.cmake:53 (message):
Host compiler appears to require libatomic, but cannot find it.
```

**Comment by vgorloff** [comment]
In `CMakeError.log` there is an error shown below.

```
Run Build Command(s):/usr/local/bin/ninja cmTC_88291 && [1/2] Building C object CMakeFiles/cmTC_88291.dir/CheckFunctionExists.c.o
[2/2] Linking C executable cmTC_88291
FAILED: cmTC_88291 
: && /Volumes/Apps/Developer/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -isystem /Volumes/Apps/Developer/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -isysroot /Volumes/Apps/Developer/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -DCHECK_FUNCTION_EXISTS=__atomic_fetch_add_4  -Werror=unguarded-availability-new -isysroot /Volumes/Apps/Developer/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/cmTC_88291.dir/CheckFunctionExists.c.o -o cmTC_88291  -latomic  -lm && :
ld: library not found for -latomic
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

This is due macOS 11.3 and/or Xcode 12.5. Will look on it.

**Comment by vgorloff** [comment]
Issue seems resolved in Release https://github.com/vgorloff/swift-everywhere-toolchain/releases/tag/1.0.67

**Comment by ephemer** [comment]
Awesome work @vgorloff!

**Comment by michaelknoch** [comment]
thanks a lot @vgorloff !
