### ISSUE TITLE
SIGSEGV when calling print()

### ISSUE THREAD

**Issue by agisboye** [vgorloff/swift-everywhere-toolchain#122]
Hi @vgorloff,

I upgraded to the Swift 5.4.1 toolchain and I've encountered an issue. As soon as I call `print()` in Swift, the Android app crashes with the following error:

`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 15101 (.home.hello_ndk), pid 15101 (.home.hello_ndk)`

Some observations:
- It happens in both my own project and your [swift-everywhere-samples](https://github.com/vgorloff/swift-everywhere-samples). Try it by calling `print("Hello")` in the `initialize()` function.
- It doesn't matter what I print.
- It happens regardless of whether I build the toolchain myself or use your prebuilt one.

I'm aware it's not necessarily an issue with your toolchain but I was wondering if you've encountered the same thing. I suppose a workaround is to remove all print statements but since my Swift framework is also used on other platforms, I'd rather not do that.

**Comment by vgorloff** [comment]
Interesting, but I can't reproduce issue on Android device or Android Simulator.

The SIGSEGV / SEGV_MAPERR seems about null pointer access or access to the corrupted memory.

**Comment by agisboye** [comment]
I tried running on a device and it appears to work. So I think the issue is with the emulator. What version are you using? I'm on 30.6.5.

**Comment by vgorloff** [comment]
ATM I'm using 30.5.6 with Android 8 and Android 11 . Let me try to update to 30.6.5.

**Comment by vgorloff** [comment]
Android 11 on simulator software 30.6.5 works without crashes on my side.

**Comment by agisboye** [comment]
The only solution I could find was to use the x64 simulator image instead of the 32-bit one. I haven't had any issues since so I'll go ahead and close the issue. Thanks for all your work!
