### ISSUE TITLE
error: no such module 'Darwin.C' @_exported import Darwin.C while compile

### ISSUE THREAD

**Issue by kmitj** [vgorloff/swift-everywhere-toolchain#125]

**Comment by vgorloff** [comment]
Would be nice to have some context. E.g. last entries from log-file or terminal output.

**Comment by buttaface** [comment]
Your code is likely Darwin/linux-only and [missing Glibc imports like this](https://github.com/apple/swift-argument-parser/pull/14/files), which all non-Mac/Windows platforms like Android require.
