### ISSUE TITLE
Forgotten licenses for llbuild and spm

### ISSUE THREAD

**Issue by vgorloff** [vgorloff/swift-everywhere-toolchain#84]
TODO

- Copy licensed during executing install action.

**Comment by Guang1234567** [comment]
https://github.com/vgorloff/swift-everywhere-toolchain/releases/tag/1.0.57

```bash
${HOME}/dev_kit/sdk/swift_source/swift-android-toolchain/usr/bin/swift-build
dyld: Library not loaded: @rpath/libCommands.dylib
  Referenced from: /Users/lihanguang/dev_kit/sdk/swift_source/swift-android-toolchain/usr/bin/swift-build
  Reason: image not found
```

Maybe forgot to copy `libCommands.dylib`? thanks.

**Comment by vgorloff** [comment]
True. It is forgotten alongside with other libraries. The whole folder `lib` wasn't copied :0

```
find ./ToolChain/Build/ -iname libCommands.dylib
./ToolChain/Build//darwin-host/spm/lib/libCommands.dylib
```

Will release version 1.0.58 today later.

btw: How I can reproduce error on my side? What should I build to get that error?

Thank you in advance!

**Comment by Guang1234567** [comment]
> btw: How I can reproduce error on my side? What should I build to get that error?

Download the toolchain_[1.0.57](https://github.com/vgorloff/swift-everywhere-toolchain/releases/tag/1.0.57)

then type 

```bash
${HOME}/dev_kit/sdk/swift_source/swift-android-toolchain/usr/bin/swift-build
```

Error will be reproduce, that is all. 

Thanks.

**Comment by Guang1234567** [comment]
The other item (maybe 😂  ):

Could you replace the `LICENSE.TXT` of `LLVM` to `LICENSE.txt`?  Because my macOS `case sensitive` 😂  .

```
# installer.js

  files.push(`${Paths.sourcesDirPath(Components.llvm)}/LICENSE.txt`);

```

**Comment by vgorloff** [comment]
Fixed in https://github.com/vgorloff/swift-everywhere-toolchain/releases/tag/1.0.58
