### ISSUE TITLE
rpath ?

### ISSUE THREAD

**Issue by johnburkey** [vgorloff/swift-everywhere-toolchain#89]
dyld: Library not loaded: @rpath/libCommands.dylib
  Referenced from: /Users/johnburkey/brightenTools/swift-android-toolchain/usr/bin/swift-build
  Reason: image not found

**Comment by vgorloff** [comment]
Should be already fixed in [#84]. 

See https://github.com/vgorloff/swift-everywhere-toolchain/pull/85/files#diff-03bb790c0cb7b352141bf95e182be6666a2a7af2914f70ec7df72eccf85d41ebR62

**Comment by vgorloff** [comment]
You can try this release: https://github.com/vgorloff/swift-everywhere-toolchain/releases/tag/1.0.58

**Comment by johnburkey** [comment]
I have already tried that one- maybe reproduce there by renaming the directory structure where your stuff built and then you downloading the release and trying it ?

If that doesn’t repro I would:

Make a new account on your Mac and download your release and run the swift build.

If that doesn’t repro I would:

Ask a local friend to try it?

It looks like an rpath issue but im not that versed in the reasons why the rpath stuff fails, and the other big change in dylib loading is the apple gatekeeper stuff.  Just a thought.    Apple has a way of silently failing things without much explanation in these areas.

- John

**Comment by vgorloff** [comment]
Ok. Here is how `LC_RPATH` looks for `swift-build` which comes with Xcode.

```sh
$ otool -l /Volumes/Apps/Developer/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build | grep RPATH -A2
          cmd LC_RPATH
      cmdsize 64
         path @executable_path/../../../../../SharedFrameworks (offset 12)
--
          cmd LC_RPATH
      cmdsize 56
         path @executable_path/../lib/swift/pm/llbuild (offset 12)
--
          cmd LC_RPATH
      cmdsize 40
         path @executable_path/../ (offset 12)
```

An here is how it looks in Android toolchain:

```sh
$ otool -l /Volumes/Shared/Git/MyProjects/swift-everywhere-toolchain/ToolChain/swift-android-toolchain/usr/bin/swift-build | grep RPATH -A2
          cmd LC_RPATH
      cmdsize 112
         path /Volumes/Shared/Git/MyProjects/swift-everywhere-toolchain/ToolChain/Build/darwin-host/spm/lib (offset 12)
--
          cmd LC_RPATH
      cmdsize 112
         path /Volumes/Shared/Git/MyProjects/swift-everywhere-toolchain/ToolChain/Build/darwin-host/llbuild/lib (offset 12)
--
          cmd LC_RPATH
      cmdsize 128
         path /Volumes/Shared/Git/MyProjects/swift-everywhere-toolchain/ToolChain/Build/darwin-host/swift-tools-support-core/lib (offset 12)
```

Absolute paths are used :0

**Comment by johnburkey** [comment]
😭

**Comment by vgorloff** [comment]
Should be fixed in https://github.com/vgorloff/swift-everywhere-toolchain/releases/tag/1.0.59.

**Comment by johnburkey** [comment]
Yeah, that bug seems gone, having trouble building .c files in SPM now, unlike your 5.2 build.

It can’t find the  c++ header stuff.   Any Ideas ?



In file included from /Users/johnburkey/Projects/Brighten2020/brightenear/CSources/CAcousticModel/Sources/cacousticmodel/tools/openfst/src/script/text-io.cc:4:
/Users/johnburkey/Projects/Brighten2020/brightenear/CSources/CAcousticModel/Sources/cacousticmodel/tools/openfst/include/fst/script/text-io.h:11:10: fatal error: 'string' file not found
#include <string>


/Users/johnburkey/Projects/Brighten2020/brightenear/CSources/CAcousticModel/Sources/cacousticmodel/tools/openfst/include/fst/script/weight-class.h:10:10: fatal error: 'memory' file not found
#include <memory>

**Comment by vgorloff** [comment]
Looks like missed header search path.
Ok. I will try to build some Swift package with C++ sources.

**Comment by johnburkey** [comment]
Thanks ☘️

**Comment by johnburkey** [comment]
Nice work dude!    I'll retest and remove our workaround.    Also I found a particular version of the bug where I had to introduce a separate c++ header path before some others, and also ran into the new clang "feature" where you can't have a struct with the same name in 2 files even with the same protecting ifdef.   I worked around that one by editing my android NDK header. :-(.   Not your bug, but perhaps theres a way to turn off the new "feature" for these builds .   Will report back with testing!

**Comment by vgorloff** [comment]
Should be fixed in https://github.com/vgorloff/swift-everywhere-toolchain/releases/tag/1.0.60.
Toolchain was built on macOS 11. May not work on Catalina :)

The order of headers sometimes plays role. One example from `CoreFoundation.h`. 

```diff
diff --git a/CoreFoundation/Base.subproj/SwiftRuntime/CoreFoundation.h b/CoreFoundation/Base.subproj/SwiftRuntime/CoreFoundation.h
index a3ebe169bb3eacd598ab804d921c2dc9389d3f60..4ceba2c11b504c20a8dc8144f46824066ae4e265 100644
--- a/CoreFoundation/Base.subproj/SwiftRuntime/CoreFoundation.h
+++ b/CoreFoundation/Base.subproj/SwiftRuntime/CoreFoundation.h
@@ -32,12 +32,12 @@
 #include <locale.h>
 #include <math.h>
 #include <setjmp.h>
+#include <time.h>
 #include <signal.h>
 #include <stddef.h>
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
-#include <time.h>
 
 #if __has_include(<netdb.h>)
 #include <netdb.h> // for Host.swift
```
